import {pergunta, resolverExpressao} from funcoes.js
const prompt = require("prompt-sync")()
let listaDeNomesDePoligonos = [
  { lados: 3, nome: "Triângulo" },
  { lados: 4, nome: "Quadrilátero" },
  { lados: 5, nome: "Pentágono" },
  { lados: 6, nome: "Hexágono" },
  { lados: 7, nome: "Heptágono" },
  { lados: 8, nome: "Octógono" },
  { lados: 9, nome: "Eneágono" },
  { lados: 10, nome: "Decágono" },
  { lados: 11, nome: "Undecágono" },
  { lados: 12, nome: "Dodecágono" },
  { lados: 13, nome: "Tridecágono" },
  { lados: 14, nome: "Tetradecágono" },
  { lados: 15, nome: "Pentadecágono" },
  { lados: 16, nome: "Hexadecágono" },
  { lados: 17, nome: "Heptadecágono" },
  { lados: 18, nome: "Octodecágono" },
  { lados: 19, nome: "Eneadecágono" },
  { lados: 20, nome: "Icoságono" },
  { lados: 21, nome: "Icosihenágono" },
  { lados: 22, nome: "Icosidigono" },
  { lados: 23, nome: "Icositrigono" },
  { lados: 24, nome: "Icositetrágono" },
  { lados: 25, nome: "Icosipentágono" },
  { lados: 26, nome: "Icosihexágono" },
  { lados: 27, nome: "Icosiheptágono" },
  { lados: 28, nome: "Icosioctágono" },
  { lados: 29, nome: "Icosieneágono" },
  { lados: 30, nome: "Triacontágono" },
  { lados: 31, nome: "Triacontahenágono" },
  { lados: 32, nome: "Triacontadigono" },
  { lados: 33, nome: "Triacontatrigono" },
  { lados: 34, nome: "Triacontatetrágono" },
  { lados: 35, nome: "Triacontapentágono" },
  { lados: 36, nome: "Triacontahexágono" },
  { lados: 37, nome: "Triacontaheptágono" },
  { lados: 38, nome: "Triacontaoctágono" },
  { lados: 39, nome: "Triacontieneágono" },
  { lados: 40, nome: "Tetracontágono" },
  { lados: 41, nome: "Tetracontahenágono" },
  { lados: 42, nome: "Tetracontadigono" },
  { lados: 43, nome: "Tetracontatrigono" },
  { lados: 44, nome: "Tetracontatetrágono" },
  { lados: 45, nome: "Tetracontapentágono" },
  { lados: 46, nome: "Tetracontahexágono" },
  { lados: 47, nome: "Tetracontaheptágono" },
  { lados: 48, nome: "Tetracontaoctágono" },
  { lados: 49, nome: "Tetracontieneágono" },
  { lados: 50, nome: "Pentacontágono" },
  { lados: 51, nome: "Pentacontahenágono" },
  { lados: 52, nome: "Pentacontadigono" },
  { lados: 53, nome: "Pentacontatrigono" },
  { lados: 54, nome: "Pentacontatetrágono" },
  { lados: 55, nome: "Pentacontapentágono" },
  { lados: 56, nome: "Pentacontahexágono" },
  { lados: 57, nome: "Pentacontaheptágono" },
  { lados: 58, nome: "Pentacontaoctágono" },
  { lados: 59, nome: "Pentacontieneágono" },
  { lados: 60, nome: "Hexacontágono" },
  { lados: 61, nome: "Hexacontahenágono" },
  { lados: 62, nome: "Hexacontadigono" },
  { lados: 63, nome: "Hexacontatrigono" },
  { lados: 64, nome: "Hexacontatetrágono" },
  { lados: 65, nome: "Hexacontapentágono" },
  { lados: 66, nome: "Hexacontahexágono" },
  { lados: 67, nome: "Hexacontaheptágono" },
  { lados: 68, nome: "Hexacontaoctágono" },
  { lados: 69, nome: "Hexacontieneágono" },
  { lados: 70, nome: "Heptacontágono" },
  { lados: 71, nome: "Heptacontahenágono" },
  { lados: 72, nome: "Heptacontadigono" },
  { lados: 73, nome: "Heptacontatrigono" },
  { lados: 74, nome: "Heptacontatetrágono" },
  { lados: 75, nome: "Heptacontapentágono" },
  { lados: 76, nome: "Heptacontahexágono" },
  { lados: 77, nome: "Heptacontaheptágono" },
  { lados: 78, nome: "Heptacontaoctágono" },
  { lados: 79, nome: "Heptacontieneágono" },
  { lados: 80, nome: "Octacontágono" },
  { lados: 81, nome: "Octacontahenágono" },
  { lados: 82, nome: "Octacontadigono" },
  { lados: 83, nome: "Octacontatrigono" },
  { lados: 84, nome: "Octacontatetrágono" },
  { lados: 85, nome: "Octacontapentágono" },
  { lados: 86, nome: "Octacontahexágono" },
  { lados: 87, nome: "Octacontaheptágono" },
  { lados: 88, nome: "Octacontaoctágono" },
  { lados: 89, nome: "Octacontieneágono" },
  { lados: 90, nome: "Eneacontágono" },
  { lados: 91, nome: "Eneacontahenágono" },
  { lados: 92, nome: "Eneacontadigono" },
  { lados: 93, nome: "Eneacontatrigono" },
  { lados: 94, nome: "Eneacontatetrágono" },
  { lados: 95, nome: "Eneacontapentágono" },
  { lados: 96, nome: "Eneacontahexágono" },
  { lados: 97, nome: "Eneacontaheptágono" },
  { lados: 98, nome: "Eneacontaoctágono" },
  { lados: 99, nome: "Eneacontieneágono" },
  { lados: 100, nome: "Hectágono" },
  { lados: 101, nome: "Hectohenágono" },
  { lados: 102, nome: "Hectodigono" },
  { lados: 103, nome: "Hectotrigono" },
  { lados: 104, nome: "Hectotetrágono" },
  { lados: 105, nome: "Hectopentágono" },
  { lados: 106, nome: "Hectohexágono" },
  { lados: 107, nome: "Hectoheptágono" },
  { lados: 108, nome: "Hectooctágono" },
  { lados: 109, nome: "Hectoteneágono" },
  { lados: 110, nome: "Hectodecágono" },
  { lados: 111, nome: "Hectoundecágono" },
  { lados: 112, nome: "Hectododecágono" },
  { lados: 113, nome: "Hectotridecágono" },
  { lados: 114, nome: "Hectotetradecágono" },
  { lados: 115, nome: "Hectopentadecágono" },
  { lados: 116, nome: "Hectohexadecágono" },
  { lados: 117, nome: "Hectoheptadecágono" },
  { lados: 118, nome: "Hectooctodecágono" },
  { lados: 119, nome: "Hectoeneadecágono" },
  { lados: 120, nome: "Hectoicoságono" },
  { lados: 121, nome: "Hectoicosihenágono" },
  { lados: 122, nome: "Hectoicosidigono" },
  { lados: 123, nome: "Hectoicositrigono" },
  { lados: 124, nome: "Hectoicositetrágono" },
  { lados: 125, nome: "Hectoicosipentágono" },
  { lados: 126, nome: "Hectoicosihexágono" },
  { lados: 127, nome: "Hectoicosiheptágono" },
  { lados: 128, nome: "Hectoicosioctágono" },
  { lados: 129, nome: "Hectoicosieneágono" },
  { lados: 130, nome: "Hectotriacontágono" },
  { lados: 131, nome: "Hectotriacontahenágono" },
  { lados: 132, nome: "Hectotriacontadigono" },
  { lados: 133, nome: "Hectotriacontatrigono" },
  { lados: 134, nome: "Hectotriacontatetrágono" },
  { lados: 135, nome: "Hectotriacontapentágono" },
  { lados: 136, nome: "Hectotriacontahexágono" },
  { lados: 137, nome: "Hectotriacontaheptágono" },
  { lados: 138, nome: "Hectotriacontaoctágono" },
  { lados: 139, nome: "Hectotriacontieneágono" },
  { lados: 140, nome: "Hectotetracontágono" },
  { lados: 141, nome: "Hectotetracontahenágono" },
  { lados: 142, nome: "Hectotetracontadigono" },
  { lados: 143, nome: "Hectotetracontatrigono" },
  { lados: 144, nome: "Hectotetracontatetrágono" },
  { lados: 145, nome: "Hectotetracontapentágono" },
  { lados: 146, nome: "Hectotetracontahexágono" },
  { lados: 147, nome: "Hectotetracontaheptágono" },
  { lados: 148, nome: "Hectotetracontaoctágono" },
  { lados: 149, nome: "Hectotetracontieneágono" },
  { lados: 150, nome: "Hectopentacontágono" },
  { lados: 151, nome: "Hectopentacontahenágono" },
  { lados: 152, nome: "Hectopentacontadigono" },
  { lados: 153, nome: "Hectopentacontatrigono" },
  { lados: 154, nome: "Hectopentacontatetrágono" },
  { lados: 155, nome: "Hectopentacontapentágono" },
  { lados: 156, nome: "Hectopentacontahexágono" },
  { lados: 157, nome: "Hectopentacontaheptágono" },
  { lados: 158, nome: "Hectopentacontaoctágono" },
  { lados: 159, nome: "Hectopentacontieneágono" },
  { lados: 160, nome: "Hectohexacontágono" },
  { lados: 161, nome: "Hectohexacontahenágono" },
  { lados: 162, nome: "Hectohexacontadigono" },
  { lados: 163, nome: "Hectohexacontatrigono" },
  { lados: 164, nome: "Hectohexacontatetrágono" },
  { lados: 165, nome: "Hectohexacontapentágono" },
  { lados: 166, nome: "Hectohexacontahexágono" },
  { lados: 167, nome: "Hectohexacontaheptágono" },
  { lados: 168, nome: "Hectohexacontaoctágono" },
  { lados: 169, nome: "Hectohexacontieneágono" },
  { lados: 170, nome: "Hectoheptacontágono" },
  { lados: 171, nome: "Hectoheptacontahenágono" },
  { lados: 172, nome: "Hectoheptacontadigono" },
  { lados: 173, nome: "Hectoheptacontatrigono" },
  { lados: 174, nome: "Hectoheptacontatetrágono" },
  { lados: 175, nome: "Hectoheptacontapentágono" },
  { lados: 176, nome: "Hectoheptacontahexágono" },
  { lados: 177, nome: "Hectoheptacontaheptágono" },
  { lados: 178, nome: "Hectoheptacontaoctágono" },
  { lados: 179, nome: "Hectoheptacontieneágono" },
  { lados: 180, nome: "Hectooctacontágono" },
  { lados: 181, nome: "Hectooctacontahenágono" },
  { lados: 182, nome: "Hectooctacontadigono" },
  { lados: 183, nome: "Hectooctacontatrigono" },
  { lados: 184, nome: "Hectooctacontatetrágono" },
  { lados: 185, nome: "Hectooctacontapentágono" },
  { lados: 186, nome: "Hectooctacontahexágono" },
  { lados: 187, nome: "Hectooctacontaheptágono" },
  { lados: 188, nome: "Hectooctacontaoctágono" },
  { lados: 189, nome: "Hectooctacontieneágono" },
  { lados: 190, nome: "Hectoeneacontágono" },
  { lados: 191, nome: "Hectoeneacontahenágono" },
  { lados: 192, nome: "Hectoeneacontadigono" },
  { lados: 193, nome: "Hectoeneacontatrigono" },
  { lados: 194, nome: "Hectoeneacontatetrágono" },
  { lados: 195, nome: "Hectoeneacontapentágono" },
  { lados: 196, nome: "Hectoeneacontahexágono" },
  { lados: 197, nome: "Hectoeneacontaheptágono" },
  { lados: 198, nome: "Hectooctacontaoctágono" },
  { lados: 199, nome: "Hectoeneacontieneágono" },
  { lados: 200, nome: "Dihectágono" }
]
console.log("você tem o numero de lados, angulos ou o nome da forma geométrica?")
let perguntaSecundaria = prompt("R:").toLowerCase()
if (perguntaSecundaria == "lados") {
    console.log("quantos?")    
    numeroDeLados = Math.floor(Number((prompt("R:"))))
    numeroDeAngulos = numeroDeLados
    somaDosAngulosInternos = (numeroDeLados - 2) * 180 + "°"
    numeroDeDiagonais = (numeroDeLados * (numeroDeLados - 3)) / 2
    if (numeroDeDiagonais % 2 !== 0) {
        numeroDeDiagonais = Math.floor(numeroDeDiagonais)
    }
    console.log("o numero de diagonais é: " + numeroDeDiagonais)
    console.log("a soma dos angulos internos é " + somaDosAngulosInternos)
    if (numeroDeLados <= 200 && numeroDeLados > 3) {
    console.log("é um " + listaDeNomesDePoligonos.find(item => item.lados === numeroDeLados).nome + "!")
  }
  else if (numeroDeLados > 200){
    console.log("é um polígono de " + numeroDeLados + " lados!")
  }
  if (numeroDeLados = 3) {
    console.log("o que quer fazer?\n1.dar/achar a medida dos lados\n2. achar os angulos\nachar")
  }
    console.log("o que quer fazer?\n1. dar/achar a medida dos lados\n2. achar os angulos\n4.trigonometria")
    let perguntaTerciaria = prompt("R:").toLowerCase()
    if (perguntaTerciaria == "1" || perguntaTerciaria == "1." || perguntaTerciaria == "dar/achar a medida dos lados" || perguntaTerciaria == "d/a" || perguntaTerciaria == "d" || perguntaTerciaria == "lados" || perguntaTerciaria == "medida dos lados") {
      
    }
    else if (perguntaTerciaria == "2." || perguntaTerciaria == "2" || perguntaTerciaria == "achar os angulos" || perguntaTerciaria == "achar angulos" || perguntaTerciaria == "a" || perguntaTerciaria == "angulos" || perguntaTerciaria == "medida dos angulos"){

    }
    else if (perguntaTerciaria == "3." || perguntaTerciaria == "3" || perguntaTerciaria == "trigonometria" || perguntaTerciaria == "t") {
    
    }
    
}
  else if (perguntaSecundaria == "angulos") {
    console.log("")
  }